### ISSUE TITLE
Split Puppet module out of plugins repo

### ISSUE THREAD

**Issue by lukebigum** [choria-io/mcollective-choria#301]
RI, are you open to splitting the Puppet module away from the Choria plugins at all?  I found it hard to build and test #300 internally because the root of the Puppet module is not the root of the Git repository.  Normally I would fork something into our corporate Git Lab, patch and test it here, then push to Github fork to create a Pull Request.

For choria-io/mcollective-choria I had to pull just the 'module' subdir into our Git Lab, patch it, test it on a Master with r10k (which broke because all the plugin files had suddenly gone missing), then copy the changes back into a different module that was a true fork of choria-io/mcollective-choria in order to create the PR. I'd also be able to write Puppet Rspec tests for it and separate them from the Ruby plugin code.

Of course if it's just me that has this problem, it might not be worth the effort.

**Comment by ripienaar** [comment]
It's a bit of a weird one because primarily this project is a ruby project and thats just how it is, so should I move those into the module - it becomes almost impossible to do the ruby dev correctly.

I can split the module - but then you'll still be faced with having to combine these ruby bits with the module.  Not really a great solution to the problem.

Fwiw I think the federation broker stuff being here is just the wrong place, a new fed broker is under development written in Go and it will get its own module or go into the main mcollective module (which will probably merge with this one)

So I don't know, I'd like to make it easier but with how things are its hard and I know I have some big restructuring coming up with new NATS based network broker + Fed Broker combination in a 'choria' binary, same binary will eventually replace the ruby mcollectived.  

This binary is already quite far along so I'd likely hold off doing this till thats ready.  Will keep this one open to remind me

**Comment by lukebigum** [comment]
That makes sense. If  this is 90% Ruby Choria and 10% Puppet it's probably not doing work to separate things.  Your Ruby-Fu is better than mine - is it possible to run append some Puppet Rspec tests from inside the module directory? That way if I send any more PRs I'm flying less blind :-)

**Comment by ripienaar** [comment]
You could add some normal rspec puppet stuff yes and then add a rake task to run those specifically and also add it as a dependency to the `release` task.

tbh though, this module should just be `init.pp`, federation should become a module on its own, will do that soon with the go stuff, so I wouldnt spend too much time on it if I was you :)

**Comment by lukebigum** [comment]
OK I'll leave it then.
