### ISSUE TITLE
allow playbook outputs to be summarized

### ISSUE THREAD

**Issue by ripienaar** [choria-io/mcollective-choria#416]
When a playbook outputs a `TaskResults` we should detect that and summarize them in a pretty manner - but should be possible to disable it and show the raw output as now

**Comment by vjanelle** [comment]
@ripienaar to continue from slack, could either make this into a function, or just detect if the last value is a `String` or not - if it is one, just `puts` the value - this would let people use `epp()` to render the final output - otherwise it would use the current json encoding.

Otherwise, a specific function as the last return value?

**Comment by ripienaar** [comment]
lets add the string detection for now and just print that in addition to what we have now - this seem a easy goal while I free some cycles to think about outputs in more detail

**Comment by ripienaar** [comment]
thanks @vjanelle
