### ISSUE TITLE
Make TLS validate mode configurable

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [choria-io/mcollective-choria#575]
In case when middleware is behind the firewall for the clients, one can use SSH port-forwarding to connect to it and to PuppetDB for nodes discovery.

However, if there is certificate mismatch, then `mco` client will hang and just won't work.

It would be cool to have `OpenSSL::SSL::VERIFY_PEER` in https://github.com/choria-io/mcollective-choria/blob/master/lib/mcollective/util/choria.rb configurable, so you can force it to `VERIFY_NONE`.

**Comment by ripienaar** [comment]
I am not really keen on this to be honest, the moment this toggle exist everyone will just set it and take the "easy" route to deployment - leading to no-one being secure.

We had this situation for years with mcollective where literally no-one deployed a secure mcollective setup because it was all too hard.  One of the major innovations and achievements of choria as regard to the deployment story is by making security easy and ubiquitous.  

The middleware is a plain TCP connection - no SSL - it starts TLS once connected and what I would suggest is making a certificate with common names matching where you will connect, I believe this will work for the tcp port forward scenario too.

**Comment by mateusz-gozdek-sociomantic** [comment]
Right, that's what I thought too. It could still be useful to make it configurable in a way, so maybe higher verification modes can be used then.

Feel free to close then and thanks for quick feedback!

**Comment by ripienaar** [comment]
In reality it is configurable. You can turn off TLS completely and even choria protocol level PKI security - not sure about verification specifically but you might as well turn TLS off if you don’t use verification. 

The way it’s adjustable is by taking the burden of packaging on yourself. You have to recompile the choria package and carry a tiny patch to the client - set 1 variable. 

I recognise security isn’t always for everyone but I consider the official release merely a “distribution” of choria and others can exist for example for internal use. I make all the tools for having your own distribution available to you but it needs to be clear that your unique distribution isn’t something I could support. For example on my very large multi 100k node deploy I run my own distribution because I want to tweak some defaults and compile in proprietary plugins. 

That’s the approach I am taking for the moment might change later but that’s where we are at. 

We have made all the security stuff - paths to certs etc - settable soecifically not by puppet only magic so they should you be in a bind with cert names you can with relative easy adjust configuration to use certs with appropriate common names etc - happy to help you find those settings.
