### ISSUE TITLE
module is trying to install gem's with apt

### ISSUE THREAD

**Issue by whohoho** [choria-io/mcollective-choria#603]
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install nats-pure=0.5.0' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package nats-pure
Error: /Stage[main]/Mcollective_choria/Mcollective::Module_plugin[mcollective_choria]/Package[nats-pure]/ensure: change from 'purged' to '0.5.0' failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install nats-pure=0.5.0' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package nats-pure
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install choria-mcorpc-support=2.20.7' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package choria-mcorpc-support
Error: /Stage[main]/Mcollective_choria/Mcollective::Module_plugin[mcollective_choria]/Package[choria-mcorpc-support]/ensure: change from 'purged' to '2.20.7' failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install choria-mcorpc-support=2.20.7' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unable to locate package choria-mcorpc-support
Notice: /Stage[main]/Mcollective_choria/Mcollective::Module_plugin[mcollective_choria]/File[/var/lib/puppet/mcollective/util/choria]: Dependency Package[nats-pure] has failures: true
Notice: /Stage[main]/Mcollective_choria/Mcollective::Module_plugin[mcollective_choria]/File[/var/lib/puppet/mcollective/util/choria]: Dependency Package[choria-mcorpc-support] has failures: true

**Comment by ripienaar** [comment]
Do you do something weird like `Package{ provider => apt}` somewhere in your other manifests?

These lines are created by:

https://github.com/choria-io/mcollective-choria/blob/9185b11330337e3a617a75e87732de6b0d409c83/module/choria/data/plugin.yaml#L4

which uses:

https://github.com/choria-io/puppet-mcollective/blob/75830124860aece4872bb86419ceef96b4c32a2f/manifests/module_plugin.pp#L62-L71

Which relies on `puppet_gem` provider due to:

https://github.com/choria-io/puppet-mcollective/blob/75830124860aece4872bb86419ceef96b4c32a2f/data/common.yaml#L72

So I suspect something in your manifests are overriding this setting

**Comment by ripienaar** [comment]
closing, please re-open if still an issue
